name: exapmle_docker_pinger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  intl: any
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_localization: ^0.3.1
  http: ^1.3.0
  go_router: ^14.8.1
  dio: ^5.8.0+1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true