name: exapmle_docker_pinger
description: "Docker container pinger."
publish_to: "none"
version: 1.1.0

environment:
  sdk: ^3.6.0

dependencies:
  intl: ^0.19.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # localizely_sdk: ^2.6.4
  http: ^1.3.0
  go_router: ^14.8.1
  dio: ^5.8.0+1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  mockito: ^5.4.6
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
# flutter_intl:
#   enabled: true
#   localizely:
#     ota_enabled: true
