name: CI Pipeline for Admin

on:
  workflow_dispatch:
  push:
    paths:
      - 'admin/**'
  pull_request:
    paths:
      - 'admin/**'

jobs:
  test: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python tests
        run: pytest